
<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta content='text/html; charset=utf-8' http-equiv='Content-Type' />

<!-- fonts -->

<title>MaycDance Welcome</title>
<link href='//juliedewaroquier.format.com/stylesheet.css' media='screen' rel='stylesheet' type='text/css' /> <!-- NOTE: this is what is generated by the theme CSS template -->

<link href='https://static2.format.com/static/title/title_23/stylesheets/style-7fb3dae0ac02796feb964c3011b165b88355336f447502f47e34f533b665d32b.css' media='screen' rel='stylesheet' type='text/css' />


<style type='text/css'>
.youtube_cont.preview, .vimeo_cont.preview{position:relative;}
.youtube_cont.preview img, .vimeo_cont.preview img{max-width: 100%; max-height: 100%; height: 100%; z-index: 1; position: absolute; left: 0; right: 0; margin-left: auto; margin-right: auto;}
.youtube_cont.preview .load_iframe, .vimeo_cont.preview .load_iframe{left: 0; position: absolute; width: 100%; height: 100%; background-repeat: no-repeat; background-position: center center; background-image: url('https://static2.format.com/static/vid_overlay-b935013b5cebeedb8f5d5f3e7b0c48ee08c556e2db6888045b216f172195e632.png'); z-index: 2;}
.youtube_cont.preview iframe, .vimeo_cont.preview iframe{left: 0; position: absolute; width: inherit; height: inherit; z-index: 1000;}
</style>

<script>
  window._4ORMAT = window._4ORMAT || {};
  window._4ORMAT.social = {
    instagram: {
      accessToken: null
    }
  }
</script>

</head>

<body class="page-535395 content content_page ">

<div id="content_page_outer" data-content-module-id="81018" data-content-module-unique-id="" data-content-module-removable="false" data-content-module-category="">
  <div class="_4ORMAT_content_page_TITLE _4ORMAT_content_page_fullwidth" id="content_page_wrapper">
    <div data-background-image="images/bg.jpg" data-editable-type="background-image" id="full_screen_image"
         style="background-image: url('http://www.maycdance.cn/img/111.jpg');" ></div>
    <h2 class="_4ORMAT_content_pages_title">
      <div data-croppable="false" data-editable-type="image" data-linkable="true" id="title_1" data-default-img="images/link_image.png" data-dom-id="title_1" data-link-type="internal" data-link-value="31284" data-content-module-unique-id="">

  <a href="/" >

<img src="{{ asset("img/2221.png") }}"  alt="Surreal fine art photography" />

  </a>


</div>
    </h2>
  </div>
</div>

      
    
  



  
<!-- -->





<style type="text/css">
  /* Image Protection */
  #image_protection_notice {
    color: #000;
    padding: 8px 8px;
    width: 200px;
    font-size: 11px;
    font-family: Arial, Helvetica, sans-serif;
    margin: 0;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    border-radius: 4px;
    background: #fff;
    box-shadow: 0 0 5px #222;
    -webkit-box-shadow: 0 0 5px #222;
    -moz-box-shadow: 0 0 5px #222;
    box-shadow: 0 0 5px #222
  }
</style>

</body>

